services:
  app:
    image: lynx
    build: .
    command: /app/init.sh
    ports:
      - 8080:2323
    working_dir: /app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - lynx-mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: unissued-crinkly-crystal-corral
      MYSQL_DATABASE: lynx

volumes:
  lynx-mysql:
