secrets:
  db_password:
    file: docker/db_password.txt
  email_password:
    file: docker/email_password.txt
  jwt_secret:
    file: docker/jwt_secret.txt

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: lynx
    command: /app/docker/init.sh
    ports:
      - 8080:2323
    working_dir: /app
    depends_on:
      - mysql
    secrets:
      - db_password
      - email_password
      - jwt_secret
    environment:
      LYNX_CREDENTIALS_FILE: docker/credentials.json

  mysql:
    image: mysql:8.0
    volumes:
      - lynx-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: lynx
    secrets:
      - db_password

volumes:
  lynx-mysql:
